name: Latest ORCID Publications
on:
  schedule:
    # Runs every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-publications:
    name: Update README with ORCID papers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # This URL generates a feed from your ORCID profile
          feed_list: "https://orcid.org/0000-0003-0371-8475/public-record.rss"
          comment_tag_name: "ORCID"
          template: "- [$title]($url) ($date)"
          max_post_count: 5
